### ISSUE TITLE
API - Finishing the Registration endpoint

### ISSUE THREAD

**Issue by gebz97** [gebz97/mandulis-ticketing-system#2]
Some rough edges need to be smoothed out with the registration logic

**Comment by thesarfo** [comment]
I can work on this

**Comment by gebz97** [comment]
> I can work on this

Make sure you pull the latest master branch

**Comment by thesarfo** [comment]
this issue can be closed now? @gebz97 
=

**Comment by gebz97** [comment]
Amazing work man 💪 🫡
